---
title: "risk perception"
output: html_document
date: "2022-10-29"
---


```{r setup, include=FALSE}
library(readxl)
library(lubridate)
library(tidyverse)
library(ggplot2)
#library(lme4)
#library(lmerTest)
#library(lavaan)
```


```{r}
# read in data
data <- read_excel("data/risks.xlsx",sheet = "data")
dates <- read_excel("data/risks.xlsx",sheet = "dates")
```


```{r}
# pivot data to long format
data <- pivot_longer(data, cols= 3:17,values_to="value",names_to="wave")
 
# transform txt variables into factors
data <- data %>% 
  mutate(risk_de = factor(risk_de)) %>% 
  mutate(risk = factor(risk)) %>% 
  mutate(wave = factor(wave)) %>% 
  mutate(food = factor(food))

# merge data with date information
data <- merge(data, dates, by = "wave")
```

legend postion bottom
year limiting 
```{r, warning=FALSE}

ggplot(data = data, mapping = aes(x = start, y = value, cluster = risk)) + 
  geom_point() + 
  geom_line() +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme(plot.title=element_text(colour="blue", size = "20", face = "bold", hjust = (0.5)))


# plot3 <- plot2+theme(plot.title=element_text(colour="blue", size = "20", face = "bold", hjust = (0.5)))

#plot3 + theme(panel.background = element_rect(size = 0.2, color = "black" ))
```




# Edi's Code

```{r}
dim(data2)
names(data2)
str(data2)
```


## Remove all NA
```{r}
data_without_na <- na.omit(data2) # remove all rows that have one or more NA

dim(data_without_na)
```

Plot still looks the same
```{r}
ggplot(data = data_without_na, mapping = aes(x = start, y = value, cluster = risk)) + 
  geom_point() + 
  geom_line() +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme(plot.title=element_text(colour="blue", size = "20", face = "bold", hjust = (0.5)))
```

## Include Risks based on number of dates

Count how often each risk is included in the "without NA" dataset and select by what count will be filtered.
```{r}
count_riks <- data_without_na %>% count(risk)

count_riks %>% arrange(desc(n))

used_risks <- count_riks %>% filter(n >= 12)
used_risks

data_selected_risk <- data_without_na %>% filter(risk %in% used_risks$risk)
dim(data_selected_risk)
```

```{r}
ggplot(data = data_selected_risk, mapping = aes(x = start, y = value, cluster = risk)) + 
  geom_point() + 
  geom_line() +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme(plot.title=element_text(colour="blue", size = "20", face = "bold", hjust = (0.5)))

```

## Visualisation

Add "+ facet_wrap(~risk)"
```{r}
ggplot(data = data_selected_risk, mapping = aes(x = start, y = value, cluster = risk)) + 
  geom_point() + 
  geom_line() +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme(plot.title=element_text(colour="blue", size = "20", face = "bold", hjust = (0.5))) +
  facet_wrap(~risk)
```

Restructure code to define "cluster" within the individual geom's.
```{r}
ggplot(data = data_selected_risk, mapping = aes(x = start, y = value)) + 
  geom_point(aes(group = risk, col = risk)) + 
  geom_line(aes(group = risk, col = risk)) +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme(plot.title=element_text(colour="blue", size = "20", face = "bold", hjust = (0.5))) +
  scale_color_brewer(palette = "Paired")
```

