---
title: "Analyis of BfR's Serial Cross-Sectional Risk Perception Survey"
output: html_document
date: "2022-10-29"
---


```{r setup, include=FALSE}
library(readxl)
library(lubridate)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(lme4)
```

Read in data 
```{r}
# read in data
data <- read_excel("data/risks.xlsx",sheet = "data")
dates <- read_excel("data/risks.xlsx",sheet = "dates")
```

Wrangle data 
```{r}
# pivot data to long format
data <- pivot_longer(data, cols= 3:17,values_to="value",names_to="wave")
 
# merge data with date information
data <- left_join(data, dates, by = "wave")

# create date variable with the mid point between the start and end dates of data collection
data <- data %>% 
  mutate(date=end+(start-end)/2)

# delete NAs, create a numeric wave variable, and transform txt variables into factors
data<-data %>% 
  filter(!is.na(value)) %>% 
  mutate(wave_num=parse_number(wave)) 

  #mutate(risk_de = factor(risk_de)) %>% 
  #mutate(risk = factor(risk)) %>% 
  #mutate(wave = factor(wave)) %>% 
  #mutate(food = factor(food))

# select risks that have been measured at least twice
selection<-data %>% 
  group_by(risk) %>% 
  summarize(n_waves=n()) %>% 
  ungroup()

data<-left_join(data,selection,by="risk") %>% 
  filter(n_waves>2)

```

Create base plot 

```{r, warning=FALSE}


# plot time course of risk perception
ggplot(data = data, mapping = aes(x = date, y = value, cluster = risk)) + 
  geom_line(color="grey") +
  ylim(c(-10,100)) +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme_minimal() +
  theme(legend.position = "none") +
   scale_x_datetime(limits = as.POSIXct(strptime(c("2014-01-01 12:00","2025-12-01 12:00"), 
                                                 format = "%Y-%m-%d %H:%M"))) 
   
ggsave("base.jpg")
```

Base plot + 1 highlight... 

```{r, warning=FALSE}

data_sel<- data %>% 
  filter(risk_de=="Antibiotikaresistenzen")
  
data_label<- data %>% 
  filter(risk_de=="Antibiotikaresistenzen") %>% 
  filter(date==max(date))

# plot time course of risk perception
ggplot(data = data, aes(x = date, y = value, cluster = risk)) + 
  geom_line(color="grey") +
  ylim(c(-10,100)) +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme_minimal() +
  theme(legend.position = "none") +
   scale_x_datetime(limits = as.POSIXct(strptime(c("2014-01-01 12:00","2025-12-01 12:00"), 
                                                 format = "%Y-%m-%d %H:%M"))) +
  geom_line(data=data_sel,mapping=aes(x = date, y = value),color="skyblue",linewidth=2) +
  geom_text(data=data_label,size=4.5,mapping=aes(label=risk,
                                        x = as.POSIXct(strptime("2022-10-01 12:00",format = "%Y-%m-%d %H:%M")), 
                                        y = value),color="skyblue",lwd=2,hjust=0) 

ggsave("highlight1.jpg")
```

Base plot + 1 highlight... 

```{r, warning=FALSE}

data_sel<- data %>% 
  filter(risk_de=="Microplastik in Lebensmitteln")
  
data_label<- data %>% 
  filter(risk_de=="Microplastik in Lebensmitteln") %>% 
  filter(date==max(date))

# plot time course of risk perception
ggplot(data = data, aes(x = date, y = value, cluster = risk)) + 
  geom_line(color="grey") +
  ylim(c(-10,100)) +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme_minimal() +
  theme(legend.position = "none") +
   scale_x_datetime(limits = as.POSIXct(strptime(c("2014-01-01 12:00","2025-12-01 12:00"), 
                                                 format = "%Y-%m-%d %H:%M"))) +
  geom_line(data=data_sel,mapping=aes(x = date, y = value),color="orange",linewidth=2) +
  geom_text(data=data_label,size=4.5,mapping=aes(label=risk,
                                        x = as.POSIXct(strptime("2022-10-01 12:00",format = "%Y-%m-%d %H:%M")), 
                                        y = value),color="orange",lwd=2,hjust=0) 

ggsave("highlight2.jpg")
```


Base plot + 2 highlights... 

```{r, warning=FALSE}

data_sel<- data %>% 
  filter(risk_de=="Lebensmitllehygiene zu hause" | risk_de=="Lebenmitllehygiene gastronomie")
  
data_label<- data %>% 
  filter(risk_de=="Lebensmitllehygiene zu hause" | risk_de=="Lebenmitllehygiene gastronomie") %>% 
  group_by(risk_de) %>% 
  filter(date==max(date)) %>% 
  ungroup()

# plot time course of risk perception
ggplot(data = data, aes(x = date, y = value, cluster = risk)) + 
  geom_line(color="grey") +
  ylim(c(-10,100)) +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme_minimal() +
  theme(legend.position = "none") +
   scale_x_datetime(limits = as.POSIXct(strptime(c("2014-01-01 12:00","2025-12-01 12:00"), 
                                                 format = "%Y-%m-%d %H:%M"))) +
  geom_line(data=data_sel,mapping=aes(x = date, y = value),color="brown",linewidth=2) +
  geom_text(data=data_label,size=4.5,mapping=aes(label=risk,
                                        x = as.POSIXct(strptime("2022-10-01 12:00",format = "%Y-%m-%d %H:%M")), 
                                        y = value),color="brown",lwd=2,hjust=0) 

ggsave("highlight3.jpg")
```

Plot all risks with labels
```{r, warning=FALSE}

# create selected set of points for annotation
data_sel<-data %>% 
  group_by(risk) %>% 
  summarize(date=max(date)) %>% 
  ungroup() %>% 
  mutate(final=1)

data_sel<-left_join(data_sel,data,by=c("risk","date")) %>% 
  filter(!is.na(final)) 

# plot time course of risk perception
ggplot(data = data, mapping = aes(x = date, y = value, cluster = risk, color=risk)) + 
  #geom_point() + 
  geom_line() +
  ylim(c(-10,100)) +
  xlab("Year") + 
  ylab("High Risk (% Sample)") + 
  theme_minimal() +
  theme(legend.position = "none") +
  geom_text_repel(data = data_sel , 
             aes(label = risk,alpha=.5), color = "black",
             box.padding = 0.5, max.overlaps = Inf) +
  scale_x_datetime(limits = as.POSIXct(strptime(c("2013-01-01 12:00","2025-01-01 12:00"), format = "%Y-%m-%d %H:%M"))) +
  facet_wrap(~(n_waves>9),nrow=2)
   
ggsave("all_annotations.jpg")
```


```{r, warning=FALSE}

model=lmer(value~1+(1|risk),data=data) # unconditional means model 
summary(model)
performance::icc(model) # icc: should be equivalent to 309.27 / (309.27+69.87)

```

```{r, warning=FALSE}

summary_data<-data %>% 
  group_by(risk) %>% 
  summarize(value=mean(value)) %>% 
  ungroup()

summary_data<-summary_data %>% 
  mutate(risk=fct_reorder(risk, value, min))

ggplot(data = summary_data, mapping = aes(x = value, y = risk)) + 
  geom_point(shape=23,fill="orange", color="orange",size=3) +
  theme_minimal() +
  geom_point(data=data,mapping = aes(x = value, y = risk),shape="|",alpha=.4,size=2) +
  xlab("High Risk (% Sample)") + 
  ylab("") +
  theme(axis.text.x = element_text(size=12),axis.text.y = element_text(size=12))

ggsave("risks_ordered.jpg")
```
