---
title: "R"
output: html_document
date: "2023-04-08"
---

```{r}
library(readxl)
library(lubridate)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(lme4)
```

```{r}
# Read Excel files
file1 <- read_excel("data/eurobarometer_data.xlsx", sheet = "import_issues_pers_de")  
file2 <- read_excel("data/inflation.xlsx",sheet = "month")
```

```{r}
# Define a mapping of seasons to months
season_to_month <- c("Jan" = 1, "Feb" = 2, "Spr" = 3, "Mar" = 3, "Sum" = 6, "Aut" = 9, "Win" = 12)

# Add a new column to data1 with the corresponding month for each season
file1$month1 <- season_to_month[file1$season]
```

```{r}

season_to_month <- function(season) {
  seasons <- c("Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")
  months <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
  return(months[match(season, seasons)])
}

# Add a new column to file2 with the corresponding number to month
file2$month1 <- season_to_month(file2$month)


```


```{r}
# Perform data merging
merged_data <- full_join(file1, file2, by = c("year", "month1")) 
```

```{r}
class(merged_data)
```
```{r}
merged_data$Verbraucherpreisindex_log <- log(merged_data$Verbraucherpreisindex)

# Create line plot with rescaled value2
ggplot(merged_data, aes(x = date, y = inflation, group = 1)) +
  geom_line(color = "blue", linetype = "solid", size = 1) +
  geom_line(aes(y = Verbraucherpreisindex_log), color = "red", linetype = "dashed", size = 1) +  # Use rescaled value2
  xlab("Date") +
  ylab("Value") +
  ggtitle("Merged Data: Value1 vs Value2 (Rescaled)") +
  theme_minimal()
```


```{r}
correlation <- cor(merged_data$inflation, merged_data$Verbraucherpreisindex)

# Create scatter plot
ggplot(merged_data, aes(x = inflation, y = Verbraucherpreisindex)) +
  geom_point() +
  labs(title = "Scatter Plot of Inflation vs Verbraucherpreisindex",
       x = "Inflation", y = "Verbraucherpreisindex") +
  geom_smooth(method = "lm", se = FALSE, linetype = "solid",
              color = "blue", aes(group = 1)) +
  annotate("text", x = min(merged_data$inflation), y = max(merged_data$Verbraucherpreisindex), hjust = 0, vjust = 1,
           label = paste0("Correlation = ", round(correlation, 2)), color = "blue")
```







